# Generated by Django 4.2.4 on 2023-09-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='upload_img',
        ),
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.question')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='polls.question'),
        ),
    ]
