# Generated by Django 4.2.4 on 2023-08-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.FloatField(max_length=10, null=True, verbose_name='Рейтинг'),
        ),
    ]
