# Generated by Django 4.2.4 on 2023-08-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rate',
        ),
    ]
