# Generated by Django 4.2.4 on 2023-08-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_rating_created_at_remove_rating_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=1000, verbose_name='Содержание'),
        ),
    ]
