# Generated by Django 4.2.4 on 2023-09-04 11:25

from django.db import migrations, models
import posts.validations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_rating_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, validators=[posts.validations.my_validation], verbose_name='Заголовок'),
        ),
    ]
