# Generated by Django 4.2.4 on 2023-08-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Содержание')),
                ('date', models.DateField(auto_now_add=True)),
                ('upload_file', models.FileField(null=True, upload_to='./uploads/news/videos/%Y/%m/%d/', verbose_name='Добавить видео')),
                ('upload_img', models.ImageField(null=True, upload_to='./uploads/news/images/%Y/%m/%d/', verbose_name='Добавить изображение')),
            ],
        ),
    ]
