# Generated by Django 4.2.4 on 2023-08-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_date_alter_news_body_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='Содержание'),
        ),
    ]
